### ISSUE TITLE
why conda env create -f environment_neutronics.yml error

### ISSUE THREAD

**Issue by fuhaocheng-cn** [fusion-energy/inertial_fusion_openmc_dagmc_paramak_example#11]
Has anyone ever encountered such a problem, and how to solve it.

Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/a/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/a/anaconda3/lib/python3.10/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/a/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/home/a/anaconda3/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 154, in execute

**Comment by shimwell** [comment]
I've not seen this one before. I would be interested to know which command was typed to generate this. Thanks for reporting
